### ISSUE TITLE
cookie duration for checkboxes

### ISSUE THREAD

**Issue by stevietv** [hueyyeng/VesperiaGuide#6]
It seems that the cookies being set for the saving of the checkboxes are only being set as valid for the session, meaning they are lost when the browser is closed.

Can you perhaps edit the checkbox.js to increase the duration. I think the `options.expires = -1` needs to be changed but not sure.

thanks for the great work!

**Comment by hueyyeng** [comment]
Hey there thanks for raising this issue!

I admit the checkboxes thingy was implemented when I'm still a greenhorn in Javascript. I'll see if I can figure out a hotfix for the checkboxes to persists after the browser is closed within this week.

Reason is in an ideal world, this guide will be:

✔ A fancy Progressive Web Application
✔️ Support Push Notifications (dunno maybe reminder after several weeks of idling)
✔️ Offline mode

Jokes aside (maybe partial joke), I will let you know when I done fixing it here.

**Comment by hueyyeng** [comment]
@stevietv I rewrote the checkbox js (which I shamelessly can't recall where I copied it off originally) and the value of the checkboxes should persist after the browser is closed.

The new JS logic is even simpler since it is using ES6 instead of jQuery... as long you're using modern browsers, it should work although I didn't test it out in Safari aka the new `Internet Explorer` for me as I don't have a Mac.

For whatever reason, the GitHub Pages build process is taking really long (already 20 mins as I'm typing this) so if the changelog page still at `0.0.21`, you will need to fetch the latest commit and serve/build your own local copy.

**Comment by stevietv** [comment]
thanks. I tried forking and also building via github pages but it also errors out. strange.
I'll try cloning and locally hosting for now in the hope that your deploy runs correctly at some point!

**Comment by stevietv** [comment]
Just saw that git hub pages has issues right now https://www.githubstatus.com/
![image](https://user-images.githubusercontent.com/1117625/160461603-e87e1c6b-8bf2-4d44-9d7d-f11d8771cc89.png)

**Comment by hueyyeng** [comment]
Guess that is the root cause on why it was taking forever. I just redeployed it and it managed to build in less than a minute.

![image](https://user-images.githubusercontent.com/15846423/160512003-3749eff6-a3c2-4a16-b87b-4c72ad1601b9.png)

**Comment by stevietv** [comment]
awesome, thanks so much for tackling this
